### ISSUE TITLE
Get this errorq

### ISSUE THREAD

**Issue by s4j33v** [Mike7154/DupCatch#10]
I repeatedly get this error:
01/04/2024 21:59:53 : An Error has Occurred
'str' object has no attribute 'SerializeToString'

**Comment by woodske** [comment]
I'm getting the same error. Here are the logs:

```
09/28/2024 14:54:53 : -------------------------------------------------------------------
09/28/2024 14:54:53 :  
09/28/2024 14:54:53 : STARTING DUPLICATES RUN
09/28/2024 14:54:53 : -------------------------------------------------------------------
09/28/2024 14:54:53 : -------------------------------------------------------------------
09/28/2024 14:54:53 : Loading the anki file C:\Users\myUser\Repos\DupCatch/anki_collection\collection-2024-09-27@18-03-39.colpkg
09/28/2024 14:54:53 : An Error has Occurred
ERROR:root:'str' object has no attribute 'SerializeToString'
Traceback (most recent call last):
  File "C:\Users\myUser\Repos\DupCatch\dupcatch.py", line 23, in <module>
    dupcatch_subs.run_duplicate_finder()
  File "C:\Users\myUser\Repos\DupCatch\dupcatch_subs.py", line 255, in run_duplicate_finder
    anki_file = initialize_database()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUser\Repos\DupCatch\dupcatch_subs.py", line 32, in initialize_database
    col.import_anki_package(file)
  File "C:\Users\myUser\AppData\Local\Programs\Python\Python312\Lib\site-packages\anki\collection.py", line 362, in import_anki_package
    log = self._backend.import_anki_package_raw(request.SerializeToString())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'SerializeToString'
```

**Comment by woodske** [comment]
Specifying an earlier version of `anki` got me past that error, but I did run into others. Replace your `requirements.txt` file with this:

```
#---------------------------------------------------------
# py -m pip install -r requirements.txt
#---------------------------------------------------------
ruamel.yaml
fuzzywuzzy[speedup]
ankisync2
anki==2.1.66
pattern
nltk
tqdm
python-slugify
pandas
numpy
```
